"""create_mandi_pipeline_and_msp_tables

Revision ID: 07580a08c5ca
Revises: 1e1bebe17e7b
Create Date: 2026-09-26 18:05:20.292530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07580a08c5ca'
down_revision: Union[str, Sequence[str], None] = '1e1bebe17e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandi_daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=150), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('arrival_date', sa.String(length=50), nullable=False),
    sa.Column('arrival_quantity', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.String(length=50), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('price_unit', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('upstream_updated_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('normalized_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_status', sa.String(length=50), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'district', 'market', 'commodity', 'variety', 'grade', 'arrival_date', name='uq_mandi_daily_record')
    )
    op.create_index('ix_mandi_commodity_date', 'mandi_daily_prices', ['commodity', 'arrival_date'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_arrival_date'), 'mandi_daily_prices', ['arrival_date'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_commodity'), 'mandi_daily_prices', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_data_status'), 'mandi_daily_prices', ['data_status'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_district'), 'mandi_daily_prices', ['district'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_id'), 'mandi_daily_prices', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_is_active'), 'mandi_daily_prices', ['is_active'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_market'), 'mandi_daily_prices', ['market'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_modal_price'), 'mandi_daily_prices', ['modal_price'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_raw_hash'), 'mandi_daily_prices', ['raw_hash'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_source'), 'mandi_daily_prices', ['source'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_source_record_id'), 'mandi_daily_prices', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_state'), 'mandi_daily_prices', ['state'], unique=False)
    op.create_index(op.f('ix_mandi_daily_prices_variety'), 'mandi_daily_prices', ['variety'], unique=False)
    op.create_index('ix_mandi_dist_comm_date', 'mandi_daily_prices', ['district', 'commodity', 'arrival_date'], unique=False)
    op.create_index('ix_mandi_state_comm_date', 'mandi_daily_prices', ['state', 'commodity', 'arrival_date'], unique=False)
    op.create_table('mandi_ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_parameters', sa.Text(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_ingestion_runs_id'), 'mandi_ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_ingestion_runs_status'), 'mandi_ingestion_runs', ['status'], unique=False)
    op.create_table('msp_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('marketing_year', sa.String(length=50), nullable=False),
    sa.Column('government_source', sa.String(length=150), nullable=False),
    sa.Column('effective_date', sa.String(length=50), nullable=False),
    sa.Column('price_per_quintal', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msp_benchmarks_commodity'), 'msp_benchmarks', ['commodity'], unique=False)
    op.create_index(op.f('ix_msp_benchmarks_id'), 'msp_benchmarks', ['id'], unique=False)
    op.create_index(op.f('ix_msp_benchmarks_is_active'), 'msp_benchmarks', ['is_active'], unique=False)
    op.create_index(op.f('ix_msp_benchmarks_marketing_year'), 'msp_benchmarks', ['marketing_year'], unique=False)
    op.create_index('ix_msp_commodity_year', 'msp_benchmarks', ['commodity', 'marketing_year'], unique=False)
    op.create_table('mandi_raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['mandi_ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_raw_records_id'), 'mandi_raw_records', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_raw_records_ingestion_run_id'), 'mandi_raw_records', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_mandi_raw_records_payload_hash'), 'mandi_raw_records', ['payload_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mandi_raw_records_payload_hash'), table_name='mandi_raw_records')
    op.drop_index(op.f('ix_mandi_raw_records_ingestion_run_id'), table_name='mandi_raw_records')
    op.drop_index(op.f('ix_mandi_raw_records_id'), table_name='mandi_raw_records')
    op.drop_table('mandi_raw_records')
    op.drop_index('ix_msp_commodity_year', table_name='msp_benchmarks')
    op.drop_index(op.f('ix_msp_benchmarks_marketing_year'), table_name='msp_benchmarks')
    op.drop_index(op.f('ix_msp_benchmarks_is_active'), table_name='msp_benchmarks')
    op.drop_index(op.f('ix_msp_benchmarks_id'), table_name='msp_benchmarks')
    op.drop_index(op.f('ix_msp_benchmarks_commodity'), table_name='msp_benchmarks')
    op.drop_table('msp_benchmarks')
    op.drop_index(op.f('ix_mandi_ingestion_runs_status'), table_name='mandi_ingestion_runs')
    op.drop_index(op.f('ix_mandi_ingestion_runs_id'), table_name='mandi_ingestion_runs')
    op.drop_table('mandi_ingestion_runs')
    op.drop_index('ix_mandi_state_comm_date', table_name='mandi_daily_prices')
    op.drop_index('ix_mandi_dist_comm_date', table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_variety'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_state'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_source_record_id'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_source'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_raw_hash'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_modal_price'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_market'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_is_active'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_id'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_district'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_data_status'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_commodity'), table_name='mandi_daily_prices')
    op.drop_index(op.f('ix_mandi_daily_prices_arrival_date'), table_name='mandi_daily_prices')
    op.drop_index('ix_mandi_commodity_date', table_name='mandi_daily_prices')
    op.drop_table('mandi_daily_prices')
    # ### end Alembic commands ###
