"""create_mandi_prices_table

Revision ID: 1e1bebe17e7b
Revises: 83c7fe2eab88
Create Date: 2026-09-26 17:38:30.220175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1bebe17e7b'
down_revision: Union[str, Sequence[str], None] = '83c7fe2eab88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandi_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('telugu_name', sa.String(length=150), nullable=True),
    sa.Column('grade_tag', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('arrival_quantity_qtl', sa.Float(), nullable=False),
    sa.Column('key_trait', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.String(length=50), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_prices_crop'), 'mandi_prices', ['crop'], unique=False)
    op.create_index('ix_mandi_prices_crop_active', 'mandi_prices', ['crop', 'is_active'], unique=False)
    op.create_index(op.f('ix_mandi_prices_district'), 'mandi_prices', ['district'], unique=False)
    op.create_index('ix_mandi_prices_district_crop', 'mandi_prices', ['district', 'crop'], unique=False)
    op.create_index(op.f('ix_mandi_prices_id'), 'mandi_prices', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_prices_is_active'), 'mandi_prices', ['is_active'], unique=False)
    op.create_index(op.f('ix_mandi_prices_market'), 'mandi_prices', ['market'], unique=False)
    op.create_index(op.f('ix_mandi_prices_modal_price'), 'mandi_prices', ['modal_price'], unique=False)
    op.create_index(op.f('ix_mandi_prices_variety'), 'mandi_prices', ['variety'], unique=False)
    op.create_index(op.f('ix_mandi_prices_verification_status'), 'mandi_prices', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mandi_prices_verification_status'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_variety'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_modal_price'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_market'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_is_active'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_id'), table_name='mandi_prices')
    op.drop_index('ix_mandi_prices_district_crop', table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_district'), table_name='mandi_prices')
    op.drop_index('ix_mandi_prices_crop_active', table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_crop'), table_name='mandi_prices')
    op.drop_table('mandi_prices')
    # ### end Alembic commands ###
